-- ============================================================
-- MK English Pro — Supabase Storage: Buckets + RLS Policies
-- Run this AFTER mk_english_pro_schema.sql
-- ============================================================

-- ------------------------------------------------------------
-- 1. CREATE BUCKETS
-- All private (public = false). Files are served via signed URLs
-- generated by the backend, never via public links.
-- ------------------------------------------------------------

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('lesson-audio', 'lesson-audio', false, 209715200, array['audio/mpeg','audio/wav','audio/mp4','audio/ogg','audio/x-m4a']),
  ('lesson-pdfs', 'lesson-pdfs', false, 52428800, array['application/pdf']),
  ('vocab-audio', 'vocab-audio', false, 10485760, array['audio/mpeg','audio/wav','audio/mp4','audio/ogg']),
  ('voice-recordings', 'voice-recordings', false, 20971520, array['audio/mpeg','audio/wav','audio/mp4','audio/webm','audio/ogg'])
on conflict (id) do nothing;

-- file_size_limit is in bytes:
--   lesson-audio: 200 MB per file (full class recordings)
--   lesson-pdfs: 50 MB per file
--   vocab-audio: 10 MB per file (short clips)
--   voice-recordings: 20 MB per file (user attempts)
-- Adjust these if your class recordings run longer than expected.

-- ------------------------------------------------------------
-- 2. PATH CONVENTION
-- Every object must be stored under a path starting with the
-- owner's user_id, e.g.:
--   {user_id}/{lesson_id}/{filename}
-- Policies below enforce that the first path segment matches
-- the requesting user's auth.uid().
-- ------------------------------------------------------------

-- Helper: storage.foldername(name) returns an array of path segments.
-- storage.foldername(name)[1] is the first folder, i.e. the user_id segment.

-- ------------------------------------------------------------
-- 3. POLICIES — one set per bucket, owner-only access
-- ------------------------------------------------------------

do $$
declare
  b text;
  buckets text[] := array['lesson-audio','lesson-pdfs','vocab-audio','voice-recordings'];
begin
  foreach b in array buckets loop

    execute format(
      $f$create policy "select_own_%1$s" on storage.objects
        for select using (
          bucket_id = %2$L
          and auth.uid()::text = (storage.foldername(name))[1]
        );$f$,
      replace(b, '-', '_'), b
    );

    execute format(
      $f$create policy "insert_own_%1$s" on storage.objects
        for insert with check (
          bucket_id = %2$L
          and auth.uid()::text = (storage.foldername(name))[1]
        );$f$,
      replace(b, '-', '_'), b
    );

    execute format(
      $f$create policy "update_own_%1$s" on storage.objects
        for update using (
          bucket_id = %2$L
          and auth.uid()::text = (storage.foldername(name))[1]
        );$f$,
      replace(b, '-', '_'), b
    );

    execute format(
      $f$create policy "delete_own_%1$s" on storage.objects
        for delete using (
          bucket_id = %2$L
          and auth.uid()::text = (storage.foldername(name))[1]
        );$f$,
      replace(b, '-', '_'), b
    );

  end loop;
end $$;

-- ------------------------------------------------------------
-- 4. EXAMPLE PATHS (for reference when building the backend)
-- ------------------------------------------------------------
-- lesson-audio/{user_id}/{lesson_id}/class_recording.mp3
-- lesson-pdfs/{user_id}/{lesson_id}/session.pdf
-- vocab-audio/{user_id}/{vocabulary_id}.mp3
-- voice-recordings/{user_id}/{drill_item_id}/{attempt_timestamp}.webm

-- ------------------------------------------------------------
-- 5. NOTES
-- ------------------------------------------------------------
-- - Since only the backend (Edge Function) performs the Google
--   Drive import, it should authenticate as the same user (or use
--   the service_role key server-side) so the resulting object path
--   still starts with that user's id and RLS is satisfied.
-- - The PWA frontend should always request a short-lived signed URL
--   (supabase.storage.from(bucket).createSignedUrl(path, expiresIn))
--   rather than relying on public URLs — buckets are private.
-- - For offline caching, the Service Worker should cache the actual
--   audio bytes fetched via the signed URL, not the signed URL itself
--   (signed URLs expire).
